apiVersion: v1
kind: ConfigMap
metadata:
  name: datasources-volume
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus-service:9090
    isDefault: true

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: 'usuarios'
        metrics_path: '/actuator/prometheus'
        scrape_interval: 5s
        static_configs:
          - targets: ['usuarios-service:8084']
