apiVersion: v1
kind: Pod
metadata:
  name: grafana
  labels:
    app: grafana
spec:
  containers:
    - name: grafana
      image: grafana/grafana:9.5.2
      ports:
        - containerPort: 3000
      volumeMounts:
        - name: datasources-volume
          mountPath: /etc/grafana/provisioning/datasources
      imagePullPolicy: IfNotPresent
  volumes:
    - name: datasources-volume
      configMap:
        name: datasources-volume
  restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: grafana-service
spec:
  selector:
    app: grafana
  ports:
    - port: 3000
      targetPort: 3000
  type: NodePort
  