apiVersion: v1
kind: Pod
metadata:
  name: prometheus
  labels:
    app: prometheus
spec:
  containers:
    - name: prometheus
      image: prom/prometheus
      ports:
        - containerPort: 9090
      volumeMounts:
        - name: config-volume
          mountPath: /etc/prometheus
      imagePullPolicy: IfNotPresent
  volumes:
    - name: config-volume
      configMap:
        name: prometheus-config
  restartPolicy: Always