global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'usuarios'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['usuarios-service:8084']